In [1]:
import tensorflow as tf
from tqdm import trange

C:\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
import numpy as np

In [8]:
with tf.Session() as sess:
    a=np.array([[1,2]] , dtype=float)
    so = tf.nn.sigmoid(a)
    
    print(sess.run(so))

[[0.73105858 0.88079708]]


In [ ]:
tf.image.crop_and_resize()

In [2]:
from tensorflow.examples.tutorials.mnist import input_data

In [3]:
from scipy.ndimage.interpolation import zoom

In [33]:
import sys

In [35]:
sys.path

['',
 'C:\\Anaconda3\\python36.zip',
 'C:\\Anaconda3\\DLLs',
 'C:\\Anaconda3\\lib',
 'C:\\Anaconda3',
 'C:\\Anaconda3\\lib\\site-packages',
 'C:\\Anaconda3\\lib\\site-packages\\contextlib2-0.5.5-py3.6.egg',
 'C:\\Anaconda3\\lib\\site-packages\\cycler-0.10.0-py3.6.egg',
 'C:\\Anaconda3\\lib\\site-packages\\keras_contrib-2.0.8-py3.6.egg',
 'C:\\Anaconda3\\lib\\site-packages\\selectivesearch-0.4-py3.6.egg',
 'C:\\Anaconda3\\lib\\site-packages\\mlxtend-0.14.0.dev0-py3.6.egg',
 'C:\\Anaconda3\\lib\\site-packages\\gumpy-0.5.0-py3.6.egg',
 'C:\\Anaconda3\\lib\\site-packages\\mne-0.17.dev0-py3.6.egg',
 'C:\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\qq122\\.ipython',
 '../']

In [6]:
vars(list)

mappingproxy({'__add__': <slot wrapper '__add__' of 'list' objects>,
              '__contains__': <slot wrapper '__contains__' of 'list' objects>,
              '__delitem__': <slot wrapper '__delitem__' of 'list' objects>,
              '__doc__': "list() -> new empty list\nlist(iterable) -> new list initialized from iterable's items",
              '__eq__': <slot wrapper '__eq__' of 'list' objects>,
              '__ge__': <slot wrapper '__ge__' of 'list' objects>,
              '__getattribute__': <slot wrapper '__getattribute__' of 'list' objects>,
              '__getitem__': <method '__getitem__' of 'list' objects>,
              '__gt__': <slot wrapper '__gt__' of 'list' objects>,
              '__hash__': None,
              '__iadd__': <slot wrapper '__iadd__' of 'list' objects>,
              '__imul__': <slot wrapper '__imul__' of 'list' objects>,
              '__init__': <slot wrapper '__init__' of 'list' objects>,
              '__iter__': <slot wrapper '__iter__' of 'l

In [12]:
print('{0},{1}'.format(2 , 3))

2,3


In [14]:
import numpy as np

In [21]:

np.random.randint(low=int(28 / 1.5), high=int(28 * 1.5))

38

In [22]:
import os

In [25]:
os.path.join('dd','ff','ds','453','d')

'dd\\ff\\ds\\453\\d'

In [27]:
import argparse

In [31]:
parser = argparse.ArgumentParser(description='PASCAL_VOC Arguments')
parser.add_argument('-n', '--year', default='2007')
parser.add_argument('-y', '--yaml', default='test')  # YAML file to override config defaults


_StoreAction(option_strings=['-y', '--yaml'], dest='yaml', nargs=None, const=None, default='test', type=None, choices=None, help=None, metavar=None)

In [32]:
os.symlink()

usage: ipykernel_launcher.py [-h] [-n YEAR] [-y YAML]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\qq122\AppData\Roaming\jupyter\runtime\kernel-45c696dc-cbae-43a3-88fb-c88442177dc5.json


SystemExit: 2

C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [36]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,2,1] , [11,22,33]])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b

array([[ 3,  2,  1],
       [11, 22, 33]])

In [41]:
np.concatenate([a,b] , axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 3,  2,  1],
       [11, 22, 33]])

In [42]:
np.concatenate([a,b] , axis=-1) #np.concatenate([a,b] , axis=1)

array([[ 1,  2,  3,  3,  2,  1],
       [ 4,  5,  6, 11, 22, 33]])

In [2]:
with tf.Session() as sess:
    comp = tf.equal([1,2],[2,2])
    
    print(sess.run(comp))

[False  True]


In [4]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4],[1,2,3,4]])

In [6]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [11]:
np.equal(a[:,0].shape , np.ones(shape=[2,1]))

array([[False],
       [False]])

In [13]:
a[:,0].shape

(2,)

In [14]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
a[[1,2]]

IndexError: index 2 is out of bounds for axis 0 with size 2