In [2]:
import numpy as np

In [4]:

a=np.array([[1.3221,1.73145],[3.19275,4.00944],[5.05587,8009892],[9.47112,4.84053],[11.2364,10.0071]])

In [7]:
a=a*32

In [8]:
a

array([[4.23072000e+01, 5.54064000e+01],
       [1.02168000e+02, 1.28302080e+02],
       [1.61787840e+02, 2.56316544e+08],
       [3.03075840e+02, 1.54896960e+02],
       [3.59564800e+02, 3.20227200e+02]])

In [9]:
a/np.array([416,416])

array([[1.01700000e-01, 1.33188462e-01],
       [2.45596154e-01, 3.08418462e-01],
       [3.88913077e-01, 6.16145538e+05],
       [7.28547692e-01, 3.72348462e-01],
       [8.64338462e-01, 7.69776923e-01]])

In [12]:
np.minimum([1,3],[2,3])

array([1, 3])

In [13]:
np.minimum(np.eye(2), [0.5, 2])

array([[0.5, 0. ],
       [0. , 1. ]])

In [14]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])