In [20]:
import numpy as np
import tensorflow as tf

In [4]:

a=np.array([[1.3221,1.73145],[3.19275,4.00944],[5.05587,8009892],[9.47112,4.84053],[11.2364,10.0071]])

In [7]:
a=a*32

In [8]:
a

array([[4.23072000e+01, 5.54064000e+01],
       [1.02168000e+02, 1.28302080e+02],
       [1.61787840e+02, 2.56316544e+08],
       [3.03075840e+02, 1.54896960e+02],
       [3.59564800e+02, 3.20227200e+02]])

In [9]:
a/np.array([416,416])

array([[1.01700000e-01, 1.33188462e-01],
       [2.45596154e-01, 3.08418462e-01],
       [3.88913077e-01, 6.16145538e+05],
       [7.28547692e-01, 3.72348462e-01],
       [8.64338462e-01, 7.69776923e-01]])

In [12]:
np.minimum([1,3],[2,3])

array([1, 3])

In [13]:
np.minimum(np.eye(2), [0.5, 2])

array([[0.5, 0. ],
       [0. , 1. ]])

In [14]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
a=np.array( [[42.3072,55.4064],[102.168,128.30208],[161.78784,256.316544],[303.07584,154.89696],[359.5648,320.2272]] )

In [2]:
np.reshape( [[42.3072,55.4064],[102.168,128.30208],[161.78784,256.316544],[303.07584,154.89696],[359.5648,320.2272]] , (2,5))


array([[ 42.3072  ,  55.4064  , 102.168   , 128.30208 , 161.78784 ],
       [256.316544, 303.07584 , 154.89696 , 359.5648  , 320.2272  ]])

In [4]:
np.reshape(a , (2,5))

array([[ 42.3072  ,  55.4064  , 102.168   , 128.30208 , 161.78784 ],
       [256.316544, 303.07584 , 154.89696 , 359.5648  , 320.2272  ]])

In [5]:
a.T

array([[ 42.3072  , 102.168   , 161.78784 , 303.07584 , 359.5648  ],
       [ 55.4064  , 128.30208 , 256.316544, 154.89696 , 320.2272  ]])

In [6]:
np.reshape([13, 13], [1, 1, 1, 1, 2]).astype(np.float32)

array([[[[[13., 13.]]]]], dtype=float32)

In [7]:
grid_w=grid_h=13

In [17]:
np.transpose( [ np.tile( np.arange(grid_w), grid_h ) , np.repeat(np.arange(grid_h), grid_w)] )

array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0],
       [11,  0],
       [12,  0],
       [ 0,  1],
       [ 1,  1],
       [ 2,  1],
       [ 3,  1],
       [ 4,  1],
       [ 5,  1],
       [ 6,  1],
       [ 7,  1],
       [ 8,  1],
       [ 9,  1],
       [10,  1],
       [11,  1],
       [12,  1],
       [ 0,  2],
       [ 1,  2],
       [ 2,  2],
       [ 3,  2],
       [ 4,  2],
       [ 5,  2],
       [ 6,  2],
       [ 7,  2],
       [ 8,  2],
       [ 9,  2],
       [10,  2],
       [11,  2],
       [12,  2],
       [ 0,  3],
       [ 1,  3],
       [ 2,  3],
       [ 3,  3],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  3],
       [ 9,  3],
       [10,  3],
       [11,  3],
       [12,  3],
       [ 0,  4],
       [ 1,  4],
       [ 2,  4],
       [ 3,  4],
       [ 4,  4],
       [ 5,  4],
       [ 6,  4

In [8]:
cxcy = np.transpose([ np.tile( np.arange(grid_w), grid_h ), np.repeat(np.arange(grid_h), grid_w) ])
        
cxcy = np.reshape(cxcy, (1, grid_h, grid_w, 1, 2))

In [18]:
np.tile( np.arange(grid_w), grid_h )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
np.repeat(np.arange(grid_h), grid_w)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [20]:
np.transpose([[1,2,3],[4,5,6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
cxcy

array([[[[[ 0,  0]],

         [[ 1,  0]],

         [[ 2,  0]],

         [[ 3,  0]],

         [[ 4,  0]],

         [[ 5,  0]],

         [[ 6,  0]],

         [[ 7,  0]],

         [[ 8,  0]],

         [[ 9,  0]],

         [[10,  0]],

         [[11,  0]],

         [[12,  0]]],


        [[[ 0,  1]],

         [[ 1,  1]],

         [[ 2,  1]],

         [[ 3,  1]],

         [[ 4,  1]],

         [[ 5,  1]],

         [[ 6,  1]],

         [[ 7,  1]],

         [[ 8,  1]],

         [[ 9,  1]],

         [[10,  1]],

         [[11,  1]],

         [[12,  1]]],


        [[[ 0,  2]],

         [[ 1,  2]],

         [[ 2,  2]],

         [[ 3,  2]],

         [[ 4,  2]],

         [[ 5,  2]],

         [[ 6,  2]],

         [[ 7,  2]],

         [[ 8,  2]],

         [[ 9,  2]],

         [[10,  2]],

         [[11,  2]],

         [[12,  2]]],


        [[[ 0,  3]],

         [[ 1,  3]],

         [[ 2,  3]],

         [[ 3,  3]],

         [[ 4,  3]],

         [[ 5,  3]],

    

In [23]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [24]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
b.shape

(2, 2, 2)

In [26]:
b[...,1]

array([[2, 4],
       [6, 8]])

In [27]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [2]:
anchors = np.array( [[42.3072,55.4064],[102.168,128.30208],[161.78784,256.316544],[303.07584,154.89696],[359.5648,320.2272]] )

In [3]:
np.reshape(anchors , (1,1,1,5,2))

array([[[[[ 42.3072  ,  55.4064  ],
          [102.168   , 128.30208 ],
          [161.78784 , 256.316544],
          [303.07584 , 154.89696 ],
          [359.5648  , 320.2272  ]]]]])

In [6]:
a=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]],[[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]])

In [16]:
with tf.Session() as sess:
    _sum = tf.reduce_sum(a[... , 0:1], axis=[1,2,3,])
    
    print(sess.run(_sum))

[22 13 13]


In [12]:
a.shape

(3, 2, 2, 3)

In [14]:
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [ 1,  2,  3]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [ 1,  2,  3]]]])

In [18]:
a[:,:,:,2].shape

(3, 2, 2)

In [19]:
a[:,:,:,2:3].shape

(3, 2, 2, 1)

In [28]:
with tf.Session() as sess:
    _max = tf.where(tf.greater([1,3],[2,2]) , [22,212],[323,33])
    
    print(sess.run(_max))

[323 212]


In [22]:
tf.reduce_prod([1,2,3,4])

<tf.Tensor 'Prod:0' shape=() dtype=int32>